version: "3"

services:
  geometry:
    build:
      context: ./api-geometria
    ports:
      - "5002:5002"
    networks:
      - math_api
  equation:
    build:
      context: ./api-equacao
    ports:
      - "5001:5001"
    networks:
      - math_api
networks:
  math_api: